---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-scheduler
  namespace: default

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scheduler-role
rules:
- apiGroups:
    - batch
  resources:
    - jobs
  verbs:
    - delete
    - list
    - create

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scheduler-role-binding
subjects:
- kind: ServiceAccount
  name: sa-scheduler
  namespace: default
roleRef:
  kind: Role
  name: scheduler-role
  apiGroup: ""
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scheduler
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sa-scheduler
          containers:
          - name: scheduler
            image: scheduler:latest
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
            env:
              - name: JOB_SERVER
                value: "http://service-server:80"
          restartPolicy: Never
