apiVersion: batch/v1
kind: Job
metadata:
  name: worker
  labels:
    jobgroup: worker-group
spec:
  template:
    metadata:
     name: worker-group
     labels:
       jobgroup: worker-group
    spec:
      containers:
      - name: worker
        image: worker:latest
        imagePullPolicy: IfNotPresent
        command: ["worker",  "2"]
        env:
        - name: JOB_SERVER
          value: "http://service-server:80"
        - name: PROMETHEUS_SERVER
          value: "http://prometheus-service:9091"
      restartPolicy: Never
  backoffLimit: 4