apiVersion: batch/v1
kind: Job
metadata:
  name: worker
  labels:
    jobgroup: worker-group
spec:
  template:
    metadata:
     name: worker-group
     labels:
       jobgroup: worker-group
    spec:
      containers:
      - name: worker
        image: worker:latest
        imagePullPolicy: IfNotPresent
        command: ["worker",  "2"]
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        env:
        - name: JOB_SERVER
          value: "http://service-server:80"
        - name: PROMETHEUS_SERVER
          value: "http://prometheus-service:9090"
      restartPolicy: Never

  backoffLimit: 4